-- Migration: create project_materials mapping table

CREATE TABLE IF NOT EXISTS project_materials (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL,
    material_id bigint NOT NULL,
    quantity numeric DEFAULT 0 NOT NULL,
    unit_price numeric DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- enforce one material per project
CREATE UNIQUE INDEX IF NOT EXISTS project_materials_project_material_uq ON project_materials(project_id, material_id);

-- optional foreign keys (uncomment if your projects/materials tables use bigint ids)
-- ALTER TABLE project_materials
--   ADD CONSTRAINT fk_pm_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
-- ALTER TABLE project_materials
--   ADD CONSTRAINT fk_pm_material FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE RESTRICT;

-- trigger to update updated_at timestamp could be added in database if desired
